// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlYv1PYwclOajQeo3_AnfwwAobWl_Ys8',
    appId: '1:844779824736:web:49d30b66106a9e274f0505',
    messagingSenderId: '844779824736',
    projectId: 'todoapp-af3e1',
    authDomain: 'todoapp-af3e1.firebaseapp.com',
    storageBucket: 'todoapp-af3e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXYvdDFV-HOuv-1JWQ1Mwp6U2EsMdOiIc',
    appId: '1:844779824736:android:de7c89d5bb5da1154f0505',
    messagingSenderId: '844779824736',
    projectId: 'todoapp-af3e1',
    storageBucket: 'todoapp-af3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVoMfRE3x1XAezpN1dDNJW2egEaSZIHE',
    appId: '1:844779824736:ios:3ba2975afe8250c24f0505',
    messagingSenderId: '844779824736',
    projectId: 'todoapp-af3e1',
    storageBucket: 'todoapp-af3e1.appspot.com',
    iosClientId: '844779824736-1lb2fu277u13pb3dnrgh2h7ukskvp3ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVoMfRE3x1XAezpN1dDNJW2egEaSZIHE',
    appId: '1:844779824736:ios:3ba2975afe8250c24f0505',
    messagingSenderId: '844779824736',
    projectId: 'todoapp-af3e1',
    storageBucket: 'todoapp-af3e1.appspot.com',
    iosClientId: '844779824736-1lb2fu277u13pb3dnrgh2h7ukskvp3ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
